#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

case $1 in
    "S-Delete")
        while read -r file; do mv -fv "$file" /tmp/; done
    ;;

    "C-c")
        cp_dir=$(:| dmenu -p 'cp dir (~/pictures/cp/<dir>):')
        mkdir -p "$HOME/pictures/cp/$cp_dir"
        while read -r file; do cp -fv "$file" "$HOME/pictures/cp/$cp_dir${cp_dir:+/}"; done
    ;;
esac
